rabbitmq:
  connections:
    conn1:
      host: "localhost"
    conn2:
      uri: "amqp://rabbit:rabbit@localhost:3333"
  exchanges:
    exch1:
      type: DIRECT
      durable: true
  queues:
    queue1:
      durable: true